// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxdgC7jKketje5ax5Da1VxFazQDvZJKgY',
    appId: '1:639034298680:web:1a34ba90c74a7dafa131cd',
    messagingSenderId: '639034298680',
    projectId: 'eam-projeto-final',
    authDomain: 'eam-projeto-final.firebaseapp.com',
    storageBucket: 'eam-projeto-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr_uiIG53J7wx9WxenUe3e6jzImrwPxP0',
    appId: '1:639034298680:android:7856c3ae639bc358a131cd',
    messagingSenderId: '639034298680',
    projectId: 'eam-projeto-final',
    storageBucket: 'eam-projeto-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfU8Z46AXOo4laJt9RavuavUlHR6KNoFk',
    appId: '1:639034298680:ios:c13006103084931ca131cd',
    messagingSenderId: '639034298680',
    projectId: 'eam-projeto-final',
    storageBucket: 'eam-projeto-final.firebasestorage.app',
    iosBundleId: 'otavio.eam',
  );
}
